[ERROR]   File "/home/dwlee/repos/loa/loa/team.py", line 121, in check
    self._check_constraints(team, league_round)
  File "/home/dwlee/repos/loa/loa/team.py", line 185, in _check_constraints
    raise ValueError(err_msg)
ValueError: [Benzi@soohnzzang] The number of units should be 10, not 0
